#!/bin/bash

if [[ $# -ne 2 ]]
then
	echo "
Usage: prefix_string [filename] [string] to prefix every line in [filename]
with the given [string]"
exit 1
fi

filename=$1
string=$2

cp $filename "$filename".bck

while read -r line
do
	echo "${string}${line}"
done < $filename > newfile

mv newfile $filename
